# Generated by Django 3.2.21 on 2023-09-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='Наименование категории')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255, verbose_name='Рецепт')),
                ('description', models.TextField(verbose_name='Описание')),
                ('recipe_image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('category', models.ManyToManyField(to='recipe_search.RecipeCategory', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255, verbose_name='Ингридиент')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество ингредиентов')),
                ('unit', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_search.recipe', verbose_name='Рецепт')),
            ],
        ),
    ]
