# Generated by Django 3.2.21 on 2023-09-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='request_number',
            field=models.IntegerField(default=1, verbose_name='Количество запросов'),
        ),
    ]
