# Generated by Django 3.2.21 on 2023-09-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_alter_telegramuser_request_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
    ]
